Preserve device symbols for better diagnostics
... when possible.

When device code compilation fails at the runtime the build log is
lacking the symbol names. For example:

```
CHIP error [TID 1984562] [1674030579.550524982] : ZE Build Log:
error: undefined reference to `'
in function: '' called by kernel: 'repro_kernel(double*, double)'

error: backend compiler failed build.
```

This is caused by dropping OpName instructions overzealously in the
SPIR-V modules which is done for working around the issue
CHIP-SPV/chip-spv#48.

Change the workaround code to drop only the OpNames that are needed
for the workaround so we see symbol names in build logs.